### PR TITLE
Displaying 1D chart, alpha-numeric data, chart area clear cleared

### PR DESCRIPTION
**Pull request by omereis**
Nexus-zip-viewer:
* Displaying 1D chart for 1D data, Heat Chart for 2D data.
* Alpha-numeric data always displayed at the bottom division.
bt7browser:
* Chart area cleared when all files un-selected

### CODE REVIEW

**Review by bmaranville — CHANGES_REQUESTED** [review]
I'm not sure why the changes to bt7browser were included in this pull request.  Please remove them.

**Review by pkienzle — CHANGES_REQUESTED** [review]
* n x 1 and 1 x n data still being displayed as 2D when it is only 1D.

    http://localhost:8000/html/nexus-zip-viewer.html?pathlist=ncnrdata+phades+201809+25566+data
    rapidscan107.nxs.phd[entry/DAS_logs/pointDetector/counts]

    http://localhost:8000/html/nexus-zip-viewer.html?pathlist=ncnrdata+cgd+201809+25482+data
    ch129554.nxz[unpolarized/DAS_logs/pointDetector/counts]

**Comment by pkienzle** [comment]
bt7browser had a change to clear the plot when there are no files selected

**Comment by bmaranville** [comment]
Thank you Omer - I merged these changes manually into the repository where this code has been migrated, as this repository is deprecated in favor of gitlab.nist.gov (internal)

**Pull request closed without merging**
